### ISSUE TITLE
add support for Emacs 24

### ISSUE THREAD

**Issue by jtimberman** [jtimberman/emacs#3]
(Was [COOK-2706](https://tickets.opscode.com/browse/COOK-2706))

Emacs 24 has been out for nearly a year, so naturally the distros don't have it. Please add support for installing it from a PPA, other distros can follow the lead.

**Comment by johnbellone** [comment]
@jtimberman I'd be willing to contribute to this. But I was wondering if its simpler to ask if you want someone to take over stewardship of cookbook?

**Comment by jtimberman** [comment]
@johnbellone I added you as a collaborator here and on supermarket. My needs for automating Emacs with Chef are now down to "package installation and git repo cloning" :smile: so I won't be using this cookbook much anymore (I have other cookbooks to handle those in a general way).

**Comment by jtimberman** [comment]
Also, Emacs 24 should be the latest default packaged version on most distributions. I'm updating the cookbook finally :cake:

**Comment by jtimberman** [comment]
Released v0.10.0 which will install Emacs 24 by default on all supported platforms.
